class Script:
    BRANDING_TAG = "\n\n<blockquote>Powered By @koreandrama006</blockquote>"
    
    # ================= Delivery & Messages =================
    AUTO_DELETE_DONE = "🗑 **আপনার ফাইলগুলো অটোমেটিক ডিলিট করা হয়েছে!**"
    INVALID_LINK = "❌ **লিংকটি ইনভ্যালিড বা এক্সপায়ার হয়ে গেছে!**"
    BATCH_SENDING = "⏳ **{total_files} টি ফাইল পাঠানো হচ্ছে... দয়া করে অপেক্ষা করুন!**"
    BATCH_SUCCESS = "✅ **আপনার সবগুলো ফাইল সফলভাবে পাঠানো হয়েছে!**"
    BATCH_SUCCESS_WARN = "✅ **আপনার সবগুলো ফাইল সফলভাবে পাঠানো হয়েছে!**\n\n⚠️ **সতর্কতা:** স্প্যাম এড়াতে ফাইলগুলো **{auto_delete_time} মিনিট** পর ডিলিট হয়ে যাবে। দয়া করে এখনই অন্য কোথাও ফরোয়ার্ড করে রাখুন।"
    FILE_NOT_FOUND_SERVER = "❌ **ফাইলটি সার্ভার থেকে মুছে গেছে!**"
    MSG_NOT_FOUND_SERVER = "❌ **মেসেজটি সার্ভার থেকে মুছে গেছে!**"
    SINGLE_SUCCESS_WARN = "⚠️ **সতর্কতা:** স্প্যাম এড়াতে ফাইলটি **{auto_delete_time} মিনিট** পর অটোমেটিক ডিলিট হয়ে যাবে। দয়া করে এখনই ফরোয়ার্ড করে রাখুন।"
    DELIVERY_ERROR = "❌ **কোনো একটি সমস্যা হয়েছে!**"
    
    # ================= Verification & Guard =================
    BYPASS_DETECTED = "🚫 **BYPASS DETECTED / INVALID SIGNATURE!** 🚫\n\nআপনি থার্ড-পার্টি বাইপাস বট ব্যবহার করেছেন অথবা অবৈধ লিংক প্রবেশ করিয়েছেন!\n\n**দয়া করে লিংকে আবার ক্লিক করে সৎভাবে অ্যাডস দেখে ভেরিফাই করুন।**"
    VERIFY_SUCCESS_TIME = "✅ **ভেরিফিকেশন সফল হয়েছে!**\n\n🎉 আগামী **{duration} ঘণ্টার** জন্য আপনি আনলিমিটেড ফাইল ডাউনলোড করতে পারবেন। আপনার কাঙ্ক্ষিত ফাইলটি পাঠানো হচ্ছে..."
    VERIFY_SUCCESS_CREDIT = "✅ **ভেরিফিকেশন সফল হয়েছে!**\n\n🎁 আপনার অ্যাকাউন্টে **{creds} টি ক্রেডিট** যুক্ত হয়েছে। আপনার কাঙ্ক্ষিত ফাইলটি পাঠানো হচ্ছে..."
    VERIFY_INVALID = "❌ **ইনভ্যালিড বা এক্সপায়ার্ড ভেরিফিকেশন টোকেন!**\nদয়া করে আবার আগের লিংকে ক্লিক করে নতুন করে ভেরিফাই করুন।"
    GENERATING_SECURE_LINK = "⏳ **Generating highly secure link...**"
    VERIFY_REQUIRED_UI = "📊 **HEY {mention},**\n\n‼️ **GET ALL FILES IN A SINGLE LINK** ‼️\n\n➪ **YOUR LINK IS READY, KINDLY CLICK ON OPEN LINK BUTTON..**"
    
    GUARD_BANNED = "🚫 **BYPASS TOOL DETECTED!**\nঅবৈধ সিগনেচার! আপনি ম্যানুয়ালি লিংক বাইপাস করার চেষ্টা করেছেন।"
    
    # ================= Start & FSub =================
    BANNED_MSG = "❌ **দুঃখিত! আপনাকে এই বট থেকে পার্মানেন্টলি ব্লক করা হয়েছে।**\n\nযে কোনো সহায়তার জন্য সাপোর্ট টিমের সাথে যোগাযোগ করুন।"
    BANNED_CB_MSG = "❌ **দুঃখিত! আপনাকে এই বট থেকে ব্লক করা হয়েছে।**"
    BANNED_CB_ALERT = "❌ আপনাকে এই বট থেকে ব্লক করা হয়েছে!"
    NEW_USER_LOG = "🆕 **New User Alert**\n\n👤 **Name:** {mention}\n🆔 **ID:** `{user_id}`\n🔗 **Started With:** `{text}`"
    PRIVATE_MODE_MSG = "🔒 **দুঃখিত! বটটি বর্তমানে প্রাইভেট মোডে আছে।**\nঅ্যাডমিন বটটি পাবলিক করলে আপনি ফাইল নিতে পারবেন।"
    FSUB_WARNING = "⚠️ **আপনাকে ফাইলটি পেতে হলে নিচের চ্যানেলগুলোতে জয়েন করতে হবে!**\n\n*(নিচের জয়েন লিংকগুলো ১০ মিনিট পর অটোমেটিক ডিলিট হয়ে যাবে)*"
    START_MSG = "👋 **হ্যালো {mention}!**\n\nআমি একটি **অ্যাডভান্সড ফাইল স্টোর বট** 🚀"
    PREMIUM_USER_TAG = "\n\n🌟 **You are a Premium User! No Ads, No Shortlinks.**"
    CREDIT_TAG = "\n\n💳 **আপনার বর্তমান ক্রেডিট:** `{creds}`"
    FSUB_NOT_JOINED_ALERT = "⚠️ আপনি এখনো সব চ্যানেলে জয়েন করেননি! দয়া করে জয়েন করুন।"
    FSUB_JOINED_ALERT = "✅ চ্যানেল ভেরিফিকেশন সফল!"
    
    # ================= Generate Link =================
    NOT_ADMIN_WARN = "⚠️ **Warning:** আপনার এই কমান্ড ব্যবহার করার অনুমতি নেই! শুধুমাত্র অ্যাডমিনরা লিংক তৈরি করতে পারেন।"
    NOT_ADMIN_SIMPLE = "⚠️ **Warning:** আপনি বটের অ্যাডমিন নন! আপনার ফাইল আপলোড বা লিংক তৈরি করার অনুমতি নেই।"
    NO_DB_SET = "❌ **আগে Database Channel সেট করুন!** `/set_db -100xxxx`"
    BATCH_START = "🟢 **Batch Link Generation Started!**\n\n➡️ **Step 1:** ডাটাবেস চ্যানেল থেকে আপনার **প্রথম ফাইলটি** এখানে ফরোয়ার্ড করুন অথবা প্রথম ফাইলের **লিংক** দিন।\n\n*(বাতিল করতে `/cancel` কমান্ড দিন)*"
    BATCH_CANCEL = "✅ **Batch process cancelled.**"
    WRONG_MSG_LINK = "❌ **সঠিক মেসেজ লিংক বা ফরোয়ার্ড করা ফাইল দিন!**"
    BATCH_STEP_2 = "✅ **First File ID Captured:** `{msg_id}`\n\n➡️ **Step 2:** এবার ডাটাবেস চ্যানেল থেকে আপনার **শেষ ফাইলটি** ফরোয়ার্ড করুন অথবা তার **লিংক** দিন।"
    GEN_BATCH_LINK_WAIT = "⏳ **Generating Batch Link...**"
    BATCH_SUCCESS_LINK = "✅ **Batch Stored Successfully! ({total_files} Files)**\n\n🔗 **Link:** `{custom_link}`"
    LOG_BATCH_LINK = "🔗 **New Batch Link**\n\n👤 **By:** {mention}\n📦 **Files:** `{total_files}`\n🔗 **Link:** `{custom_link}`"
    GEN_DB_LINK_WAIT = "⏳ **Generating Link for DB Channel Message...**"
    SINGLE_SUCCESS_LINK = "✅ **Saved!**\n🔗 **Link:** `{custom_link}`"
    LOG_SINGLE_LINK = "🔗 **New Single Link**\n\n👤 **By:** {mention}\n🔗 **Link:** `{custom_link}`"
    GEN_LINK_WAIT = "⏳ **Generating Link...**"
    FILE_EXISTS = "⚠️ **File Already Exists!**\n🔗 **Link:** `{custom_link}`"
    GEN_PERMANENT_WAIT = "**👇 Click below to generate permanent link:**"
    PROCESSING_FILE = "⏳ **Processing File...**"
    SAVED_IN_DB = "✅ **Saved in Database!**\n🔗 **Link:** `{custom_link}`"
    ERROR_MSG = "❌ **Error:** {error}"
    
    # ================= Admin Utils =================
    NOT_OWNER_WARN = "⚠️ **Warning:** শুধুমাত্র Owner এই কমান্ড ব্যবহার করতে পারবেন!"
    FETCHING_STATS = "⏳ **Fetching Unique Statistics...**"
    STATS_MSG = "📊 **Bot Advanced Statistics**\n\n⏱ **Uptime:** `{uptime}`\n👥 **Total Users:** `{total_users}`\n🚫 **Banned Users:** `{total_banned}`\n📁 **Total Files Saved:** `{total_files}`\n🗄 **Multi-DB Status:** `{multi_db_status}`\n🔗 **Shortlink:** `{sl_status} ({sl_type})`\n🛡 **Web Guard:** `{guard_status}`"
    REPLY_DBROADCAST = "❌ **সঠিক নিয়ম:** মেসেজে রিপ্লাই করে `/dbroadcast 10` (মিনিট) দিন!"
    MINUTES_NUMBER_ERROR = "❌ **মিনিট অবশ্যই সংখ্যা হতে হবে!**"
    DBROADCAST_START = "⏳ **Auto-Delete Broadcast Started ({mins} mins)...**"
    DBROADCAST_DONE = "✅ **Auto-Delete Broadcast Completed!**\n\n🟢 **Sent:** `{sent}`\n🔴 **Failed:** `{failed}`\n🗑 **Auto-Delete in:** `{mins} mins`"
    REPLY_BROADCAST = "❌ **যে মেসেজটি সবাইকে পাঠাতে চান, সেটিতে রিপ্লাই করে `/broadcast` কমান্ড দিন!**"
    BROADCAST_START = "⏳ **Broadcasting started...**"
    BROADCAST_DONE = "✅ **Broadcast Completed!**\n\n🟢 **Successfully Sent:** `{sent}`\n🔴 **Failed/Blocked:** `{failed}`"
    BAN_USAGE = "❌ **সঠিক নিয়ম:** `/ban UserID`"
    BAN_SELF = "❌ **আপনি নিজেকে ব্যান করতে পারবেন নাস**"
    BAN_SUCCESS = "🚫 **User Banned Successfully:** `{user_id}`"
    ID_NUMBER_ERROR = "❌ **ইউজার আইডি অবশ্যই সংখ্যা হতে হবে!**"
    UNBAN_USAGE = "❌ **সঠিক নিয়ম:** `/unban UserID`"
    UNBAN_SUCCESS = "✅ **User Unbanned Successfully:** `{user_id}`"
    UNBAN_ALL_SUCCESS = "✅ **Successfully unbanned {count} users!**"
    ADD_CREDIT_USAGE = "❌ **সঠিক নিয়ম:** `/add_credit UserID Amount`"
    ADD_CREDIT_SUCCESS = "✅ **Added {amount} credits to User `{user_id}`**"
    REMOVE_CREDIT_USAGE = "❌ **সঠিক নিয়ম:** `/remove_credit UserID Amount`"
    REMOVE_CREDIT_SUCCESS = "✅ **Removed {amount} credits from User `{user_id}`**"
    ID_AMOUNT_ERROR = "❌ **ID এবং Amount অবশ্যই সংখ্যা হতে হবে!**"
    SET_SL_USAGE = "❌ **সঠিক নিয়ম:** `/set_shortlink <url> <api_key>`\n*উদাহরণ:* `/set_shortlink shareus.io 123456789abc`"
    SET_SL_SUCCESS = "✅ **Shortlink API Updated Successfully!**\n\n🌐 **URL:** `{url}`\n🔑 **API Key:** `{api}`"
    SET_TUTORIAL_USAGE = "❌ **সঠিক নিয়ম:** `/set_tutorial https://t.me/your_video`\n*(টিউটোরিয়াল সরাতে `/set_tutorial off` দিন)*"
    TUTORIAL_REMOVED = "✅ **Tutorial Link Removed!**\nএখন থেকে আর টিউটোরিয়াল বাটন দেখাবে না।"
    TUTORIAL_SUCCESS = "✅ **Tutorial Link Updated Successfully!**\n\n🔗 **Link:** {link}"
    
    # ================= Settings Panel =================
    SET_DELETE_USAGE = "❌ **সঠিক নিয়ম:** `/set_delete 10` (মিনিট) অথবা `/set_delete off`"
    SET_DELETE_OFF = "✅ **Auto Delete is now OFF!**\nফাইল আর অটো-ডিলিট হবে না।"
    SET_DELETE_ON = "✅ **Auto Delete is now ON!**\nইউজারদের দেওয়া ফাইল **{mins} মিনিট** পর ডিলিট হয়ে যাবে।"
    
    SETTINGS_MSG = "⚙️ **Advanced Bot Settings Panel**\n\nনিচের বাটনগুলো ক্লিক করে বটের ভেরিফিকেশন এবং শর্টলিংক সিস্টেম কন্ট্রোল করুন:"
    NOT_OWNER_ALERT = "❌ You are not the owner!"
    SETTINGS_UPDATED_ALERT = "✅ Settings Updated!"
    
    # ================= Buttons =================
    BTN_UPDATES_CHANNEL = "📢 Updates Channel"
    BTN_CONTACT_SUPPORT = "🛠 Contact Support"
    BTN_OPEN_LINK = "▶️ OPEN LINK"
    BTN_TUTORIAL = "🎥 TUTORIAL"
    
    # 🚀 FIX: CLEAN SMALL CAPS NO EXTRA SPACES
    BTN_BUY_PREMIUM = "💎 ʙᴜʏ ᴘʀᴇᴍɪᴜᴍ"
    BTN_PREMIUM_SETTINGS = "💎 ᴘʀᴇᴍɪᴜᴍ sᴇᴛᴛɪɴɢs"
    
    BTN_CHECK_JOINED = "🔄 Check Joined"
    BTN_JOIN_CHANNEL = "🟢 Join Channel {idx}"
    BTN_ORIGINAL_LINK = "🌐 Original Link"
    BTN_GENERATE_LINK = "📁 Generate Link"
    BTN_SL_STATUS = "🔗 Shortlink: {status}"
    BTN_SL_MODE = "⚙️ Mode: {mode}"
    BTN_SL_TIME = "⏱ Verify Duration: {time} Hours 🔄"
    BTN_SL_CREDIT = "🎁 Credits: {creds} Files 🔄"
    BTN_BYPASS_TIME = "🛡 Bypass Time Guard: {time}s 🔄"
    BTN_WEB_GUARD = "🔥 Cloudflare Web Guard: {status}"
    BTN_PROTECT_CONTENT = "🔒 Protect Content: {status}"
    BTN_CLOSE_PANEL = "❌ Close Panel"
